language: python
cache: pip
sudo: false

addons:
  code_climate:
    repo_token:
      secure: "W3fmZj+FNmZm6lyDq/ChcIQwjddI8oJJIwHOwbmuSDdIa8y7HYfIFXakbAL/nGZN2jWEZ8VRsYWvEu00L8bVTrLPK0B+fYGTHZvKAJOh9kEQGRqYc/QtSmEm9rfjwG3REannRuPCz6WSuirRpNqfkk5R/ePxknq8SI6WZasmz23MMSX3zTOLqD6o62m2FTurE/Fl4Xx5lOL1d9PSbLWN6DGcOA8turHpQWfuCV8Bo95UnqeYMni/MSjo4iDDvAUEhsiv3YlBdW7SSEt4Yo0iV4H6gGGISw6zxX+eFsjQwdz0vhKn30vHKNEmvguVpCSMP/Te81yNlBk3YYUxvwJKrd73YgM0BIfqlheIdOBZywbL/Iyapr12mLuoxGLJS6PNBr8Hc2KNrQMA0+JBzQ24tl/JYauXbJI0jKM+XRw/6rNLevdOdcSlu27Db/KTBLD2JWtu5f56CwJEMEf6BQLbyvP+vCkPOdIWED3gOf9zR48i/KOmU6oTWnIV37kzx9qTpZzj8Bwxv7xm+5Vl3iaPov+mNJsyPOzeG2nBw77xZvpqw+jr8Jf+jusm9+dEpmmFPDU47cVk50qqlv+uaO2Sqvq5aFrms/WzDhi6NEsCUE3H4pBdWicipXvovW3yGNSbQhid9+Vab4ZPCtQd8uY9jRucPelwMaqPAyfQ+AsP58Q="


# Test environments
matrix:
  include:
   - env: TOXENV=py36
     python: 3.6
     dist: xenial
   - env: TOXENV=py37
     python: 3.7
     dist: xenial
   - env: TOXENV=py38
     python: 3.8
     dist: xenial

install:
  - pip install flit flake8 black tox

script:
  - tox

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
